### ISSUE TITLE
Ask for license

### ISSUE THREAD

**Issue by ebiyu** [seanavery/g29-py#2]
I want to use this repository, but I noticed that your repo doesn't contain License. Can I know which Open Source License you use if this repository is open source.

I appreciate for your great job. Thank you.

**Comment by seanavery** [comment]
Cheers! Added MIT license to the repo. 

Lmk if there is another license that makes it easier to use. Do not care about any copyright attribution parts. I am using it for a personal project. If anyone else can make use of it, great.
